Enum links and text
SkillBrain-com/Helin_Internship pull request #15
Opened 2023-06-20 21:29 UTC by MihaiSlavoiu

Added an Enum with Links and Texts

2023-06-21 13:14 UTC, ZahariaAlexC requested changes

2023-06-21 13:14 UTC, ZahariaAlexC commented on src/main/java/pages/LoginPageContactApp.java
> +    public String[] expectedAlertMessages = {"Datele de autentificare introduse nu se potrivesc cu baza de date.",
verifica si aici daca poti adauga in Enum aceasta alerta

2023-06-21 19:50 UTC, MihaiSlavoiu commented on src/main/java/pages/LoginPageContactApp.java
> +    public String[] expectedAlertMessages = {"Datele de autentificare introduse nu se potrivesc cu baza de date.",
Multumesc de observatie. Am modificat.

2023-06-22 15:48 UTC, ZahariaAlexC requested changes

2023-06-22 15:48 UTC, ZahariaAlexC commented on src/test/java/tests/CreateAccountTest.java
> -        Assert.assertTrue(createAccount().verifyemail(email),"Email incorect!");
te rog sa il rezolvi si pe acesta

2023-06-22 15:48 UTC, DanaCatavei approved these changes
ok

2023-06-22 15:49 UTC, AlexandraNegulescu approved these changes

2023-06-22 15:49 UTC, DanielIrimia87 approved these changes

2023-06-22 15:54 UTC, ZahariaAlexC approved these changes

2023-06-22 15:54 UTC, merged