Currency and bank tests
SkillBrain-com/Helin_Internship pull request #20
Opened 2023-06-26 05:13 UTC by DanielIrimia87

2023-06-29 14:04 UTC, ZahariaAlexC requested changes
verifica comentariile

2023-06-29 14:04 UTC, ZahariaAlexC commented on src/main/java/pages/SettingCompany/ActivityPage.java
> +                Assert.assertTrue(true);
nu ai rezolvat?

2023-06-29 14:04 UTC, ZahariaAlexC commented on src/main/java/pages/SettingCompany/CurrencyPage.java
> +                Assert.assertTrue(true);
nu ai rezolvat?

2023-06-29 14:04 UTC, ZahariaAlexC commented on src/main/java/pages/SettingCompany/CurrencyPage.java
> +            }
nu ai rezolvat?

2023-06-29 14:04 UTC, ZahariaAlexC commented on src/main/java/pages/SettingCompany/HousesAndBanks.java
> +            Assert.fail("Nu s-a gasit tipul de serviciu");
nu ai rezolvat?

2023-06-29 14:04 UTC, ZahariaAlexC commented on src/main/java/pages/SettingCompany/HousesAndBanks.java
> +                    Assert.assertTrue(true);
nu ai rezolvat?

2023-06-29 14:04 UTC, ZahariaAlexC commented on src/main/java/pages/SettingCompany/HousesAndBanks.java
> +                    Assert.assertTrue(true);
nu ai rezolvat?

2023-06-29 19:29 UTC, DanielIrimia87 commented on src/main/java/pages/SettingCompany/ActivityPage.java
> +                Assert.assertTrue(true);
rezolvat

2023-06-29 19:29 UTC, DanielIrimia87 commented on src/main/java/pages/SettingCompany/CurrencyPage.java
> +            }
am rezolvat

2023-06-29 19:30 UTC, DanielIrimia87 commented on src/main/java/pages/SettingCompany/CurrencyPage.java
> +                Assert.assertTrue(true);
am rezolvat

2023-06-29 19:30 UTC, DanielIrimia87 commented on src/main/java/pages/SettingCompany/HousesAndBanks.java
> +                    Assert.assertTrue(true);
am rezolvat

2023-07-04 18:23 UTC, ZahariaAlexC approved these changes

2023-07-04 18:23 UTC, dicacristian approved these changes

2023-07-04 18:23 UTC, DanaCatavei approved these changes

2023-07-04 18:24 UTC, merged